# Generated by Django 3.2.17 on 2023-09-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_subscription_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='comment',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
    ]
